version: "3.3"

services:
  db:
    image: mariadb:10.3
    volumes: ["db_data:/var/lib/mysql"]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: piga
      MYSQL_DATABASE: piga

  web:
    depends_on: [db]
    command: bin/server
    image: nymanjens/piga:latest
    ports: ["9000:9000"]
    restart: always
    environment:
      APPLICATION_SECRET: ${APPLICATION_SECRET}
      DATABASE_URL: jdbc:mysql://db:3306/piga?user=root&password=piga

volumes:
  db_data: {}
